version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: chat_postgres
    environment:
      POSTGRES_DB: ChatDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chat-password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  refi:
    image: redis
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres_data:
