version: '3.8'

networks:
  chat-net:

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
      - VITE_JWT_SECRET="secretkey123secretkey123secretkey123secretkey123secretkey123secretkey123"
      - VITE_API_URL=http://chat-app:8000
    networks:
      - chat-net
    ports:
      - "80:80"
    depends_on:
      chat-app:
        condition: service_started
    environment:
      - NODE_ENV=prod

  db:
    image: postgres:latest
    container_name: chat_postgres
    environment:
      POSTGRES_DB: ChatDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chat-password
    ports:
      - '5353:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 2s
      timeout: 5s
      retries: 10

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - chat-net
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 2s
      timeout: 5s
      retries: 10

  chat-app:
    container_name: chat-app
    image: chat-app
    build:
      context: .
      dockerfile: src/ChatApp.Api/Dockerfile
    networks:
      - chat-net
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
